litellm_settings:
  callbacks: ["token_refresher.BedrockTokenRefresher"]

model_list:
  - model_name: gpt-20b
    litellm_params:
      model: bedrock_mantle/openai.gpt-oss-20b
      api_base: "os.environ/BEDROCK_MANTLE_API_BASE"

  - model_name: gpt-120b
    litellm_params:
      model: bedrock_mantle/openai.gpt-oss-120b
      api_base: "os.environ/BEDROCK_MANTLE_API_BASE"

  - model_name: deepseek-v3
    litellm_params:
      model: bedrock_mantle/deepseek.v3.2
      api_base: "os.environ/BEDROCK_MANTLE_API_BASE"

  - model_name: qwen-coder
    litellm_params:
      model: bedrock_mantle/qwen.qwen3-coder-30b-a3b-instruct
      api_base: "os.environ/BEDROCK_MANTLE_API_BASE"
